# Generated by Django 4.1.5 on 2023-02-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0056_admin_data_user_data_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
